spring:
  application:
    name: crispix-ai
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://your-host:3306/your-database
    username: your-username
    password: your-password

